CREATE TABLE  "ACTEUR" 
   (	"NUMACTEUR" NUMBER NOT NULL ENABLE, 
	"NOM_PRENOM" VARCHAR2(200), 
	"PAYS" VARCHAR2(100), 
	"DATENAISSANCE" DATE, 
	 CONSTRAINT "ACTEUR_PK" PRIMARY KEY ("NUMACTEUR") ENABLE
   )
/
CREATE TABLE  "REALISATEUR" 
   (	"IDREALIS" NUMBER NOT NULL ENABLE, 
	"NOM_PRENOM" VARCHAR2(200), 
	"PAYS" VARCHAR2(200), 
	"DATENAISSANCE" VARCHAR2(200), 
	 CONSTRAINT "REALISATEUR_PK" PRIMARY KEY ("IDREALIS") ENABLE
   )
/
CREATE TABLE  "FILM" 
   (	"IDFILM" NUMBER NOT NULL ENABLE, 
	"TITRE" VARCHAR2(4000), 
	"ANNEREALIS" DATE, 
	"IDREALIS" NUMBER, 
	"GENRE" VARCHAR2(200), 
	 CONSTRAINT "FILM_PK" PRIMARY KEY ("IDFILM") ENABLE, 
	 CONSTRAINT "FK_FILM_REFERENCE_REALISAT" FOREIGN KEY ("IDREALIS")
	  REFERENCES  "REALISATEUR" ("IDREALIS") ENABLE
   )
/
CREATE TABLE  "ACTER" 
   (	"IDACTER" NUMBER NOT NULL ENABLE, 
	"IDFILM" NUMBER, 
	"NUMACTEUR" NUMBER, 
	 CONSTRAINT "ACTER_PK" PRIMARY KEY ("IDACTER") ENABLE, 
	 CONSTRAINT "FK_ACTER_REFERENCE_FILM" FOREIGN KEY ("IDFILM")
	  REFERENCES  "FILM" ("IDFILM") ENABLE, 
	 CONSTRAINT "FK_ACTER_REFERENCE_ACTEUR" FOREIGN KEY ("NUMACTEUR")
	  REFERENCES  "ACTEUR" ("NUMACTEUR") ENABLE
   )
/
CREATE TABLE  "CLIENT" 
   (	"IDCLIENT" NUMBER NOT NULL ENABLE, 
	"CIN" NUMBER, 
	"NOM_PRENOM" VARCHAR2(500), 
	"DATENAISSANCE" DATE, 
	"ADRESSE" VARCHAR2(4000), 
	 CONSTRAINT "CLIENT_PK" PRIMARY KEY ("IDCLIENT") ENABLE
   )
/
CREATE TABLE  "EXEMPLAIRE" 
   (	"IDXEMPLAIRE" NUMBER NOT NULL ENABLE, 
	"IDFILM" NUMBER, 
	"TYPESUPP" VARCHAR2(50), 
	 CONSTRAINT "EXEMPLAIRE_PK" PRIMARY KEY ("IDXEMPLAIRE") ENABLE, 
	 CONSTRAINT "FK_EXEMPLAI_REFERENCE_FILM" FOREIGN KEY ("IDFILM")
	  REFERENCES  "FILM" ("IDFILM") ENABLE
   )
/
CREATE TABLE  "EMPREINTE" 
   (	"IDPREINTE" NUMBER NOT NULL ENABLE, 
	"IDCLIENT" NUMBER, 
	"IDXEMPLAIRE" NUMBER, 
	"DATEEMPREINTE" DATE, 
	"DATERETOUR" DATE, 
	 CONSTRAINT "EMPREINTE_PK" PRIMARY KEY ("IDPREINTE") ENABLE, 
	 CONSTRAINT "FK_EMPREINT_REFERENCE_CLIENT" FOREIGN KEY ("IDCLIENT")
	  REFERENCES  "CLIENT" ("IDCLIENT") ENABLE, 
	 CONSTRAINT "FK_EMPREINT_REFERENCE_EXEMPLAI" FOREIGN KEY ("IDXEMPLAIRE")
	  REFERENCES  "EXEMPLAIRE" ("IDXEMPLAIRE") ENABLE
   )
/
CREATE TABLE  "PICFILM" 
   (	"IDPIC" NUMBER NOT NULL ENABLE, 
	"PIC" BLOB, 
	"IDFILM" NUMBER(*,0), 
	 CONSTRAINT "PICFILM_PK" PRIMARY KEY ("IDPIC") ENABLE
   )
/

CREATE UNIQUE INDEX  "ACTER_PK" ON  "ACTER" ("IDACTER")
/
CREATE UNIQUE INDEX  "ACTEUR_PK" ON  "ACTEUR" ("NUMACTEUR")
/
CREATE UNIQUE INDEX  "CLIENT_PK" ON  "CLIENT" ("IDCLIENT")
/
CREATE UNIQUE INDEX  "EMPREINTE_PK" ON  "EMPREINTE" ("IDPREINTE")
/
CREATE UNIQUE INDEX  "EXEMPLAIRE_PK" ON  "EXEMPLAIRE" ("IDXEMPLAIRE")
/
CREATE UNIQUE INDEX  "FILM_PK" ON  "FILM" ("IDFILM")
/
CREATE UNIQUE INDEX  "PICFILM_PK" ON  "PICFILM" ("IDPIC")
/
CREATE UNIQUE INDEX  "REALISATEUR_PK" ON  "REALISATEUR" ("IDREALIS")
/
CREATE UNIQUE INDEX  "SYS_IL0000014378C00002$$" ON  "PICFILM" (
/

